module.exports = {
    serverHost: "clipurr.ddnsfree.com",
    serverPort: "443",
    actionVideoDict: {
      "Strongly disagree": "Fa1aQVakG9c",
      "Screaming": "xmMRrD5ed1A",
      "Using a computer": "maYiKInjiQc",
      "Waking up": "S51sYLq_Z3o",
      "Watching TV": "b5yPTWfN9nA",
      "Listening but confused": "QO1bWBR_98E",
      "Listening": "sl3cWhHbnKs",
      "Playing piano": "uI0UnePf2EU",
      "Enjoying music": "hdZDnSb7QQI",
      "Going somewhere": "3uiRMEPrrmg",
      "Being surprised": "VX35ScXylf4",
      "Being excited": "nkbtMSMkPy4",
      "Judging": "L8iIED060H0",
      "Shooting a gun": "r2CNHFZZFcc",
      "Singing": "ZVmd2xuaMQM",
      "Sleeping": "C8hAGrJVXSo",
      "Sleeping2": "dROuxEoRINA",
      "Taking a selfie": "FWgMri-dOA4",
      "Talking": "srZWSMFFmR4",
      "Walking": "ynMedtbA14Q",
      "Writing": "aA0TVlLbP5c",
      "Laughing": "Fb8Rfle5-FY",
      "Loving": "rmLBeng-Pt8",
      "Moving out": "087wZQIPqO8",
      "Painting": "U11B2SS22DM",
      "Pretending to sleep": "2rYkNqYZbck",
      "Reading": "I7sRanifjw8",
      "Realizing": "S-xFNGGDvkE",
      "Running": "KY-Yqltn760",
      "Bouncing to a beat": "wR6VewEvYY8",
      "Cooking": "lXqMxRqUyrk",
      "Dancing": "Ef4c4bYhibQ",
      "Driving": "1Jp0Q1MD1BE",
      "Eating": "a06GfhnTjBQ",
      "Facing an opponent": "uSLDPg3YDro",
      "Fighting": "Hp2EWD81zV4",
      "Having a meeting": "p1QdNg3oZhI",
      "Having fun": "L7tKSPnLzYI",
      "Hitting someone": "X_3w3Ipdb2w",
      "Being happy": "qqM1-MxvZ1M",
      "Being hungry": "W1sG6-iiscw",
      "Being in a tense relationship": "8PlYIMThRH0",
      "Being sad": "gBYT8o-a_h4",
      "Being nervous": "nG7JwhU284Q",
      "Being sassy": "pyz4affOeS4",
      "Being satisfied": "UCF9hdAUqfI",
      "Being surprised2": "HW7qDFMNtN4",
      "Being tired": "1UbKL1_bIAg",
      "Being wet": "JC2B6ccrzQ0",
      "Boss talking (someone else)": "-WMNuyOIW1Q",
      "Asking": "Y7s5ppX8z7k",
      "Being afraid": "MFkSOeAGNqM",
      "Being angry": "Xa49e-q4bmY",
      "Being blind": "Tw9HsZO6QHU",
      "Being bored": "J-WSr_D2uts",
      "Being cold": "vdg8LBwXAr4",
      "Being confident": "r9BlMjtaunw",
      "Being confused": "w5g0IUayPdo",
      "Being cool": "sJ-nzxTIf70",
      "Being curious": "LJCEugEm32I",
      "Being depressed": "lm4qotdgNH4",
      "Being disgusted": "Fd50VvYg4Ug",
      "Being evil": "he3VPFtrRhM",
      "Being excited2": "T_cR7bgoJoI",
    }
  };